Repository vektorprogrammet/vektor-backend, pull requests merged in 2022-10, with the labels that each got.

#159 Fix some images not showing
  config/packages/liip_imagine.yaml
Labels: hacktoberfest-accepted

#160 VB-110: Fix Form styling missing
  config/packages/twig.yaml
Labels: hacktoberfest-accepted, PR: Good to Merge

#167 Add dp-injection for usergroupcollection
  src/Controller/UserGroupCollectionController.php
Labels: hacktoberfest-accepted

#168 Remove tests for removed functionality
  tests/Controller/ChangeLogControllerTest.php
  tests/Controller/FeedbackControllerTest.php
Labels: hacktoberfest-accepted

#166 Update target slack channel
  .env
Labels: hacktoberfest-accepted

#169 VB-118: Deprecate UserGroupCollection
  assets/scss/pages/usergroupcollection.scss
  config/routes.yaml
  src/Controller/UserGroupCollectionController.php
  src/Entity/UserGroup.php
  src/Entity/UserGroupCollection.php
  src/Form/Type/UserGroupCollectionType.php
  src/Service/UserGroupCollectionManager.php
  templates/base/admin/main_navigation.html.twig
  templates/usergroup_collection/usergroup_collection_create.html.twig
  templates/usergroup_collection/usergroup_collections.html.twig
Labels: hacktoberfest-accepted

#170 VB-112: Deprecate Undersøkelser
  config/routes.yaml
  src/Controller/SurveyController.php
  src/Controller/SurveyNotifierController.php
  src/Controller/SurveyPopupController.php
  src/Controller/WidgetController.php
  src/DataFixtures/LoadAccessRuleData.php
  src/DataFixtures/LoadSurveyData.php
  src/Entity/Survey.php
  src/Entity/SurveyAnswer.php
  src/Entity/SurveyLinkClick.php
  src/Entity/SurveyNotification.php
  src/Entity/SurveyNotificationCollection.php
  src/Entity/SurveyQuestion.php
  src/Entity/SurveyQuestionAlternative.php
  src/Entity/SurveyTaken.php
  src/Form/Type/SurveyAdminType.php
  src/Form/Type/SurveyAnswerType.php
  src/Form/Type/SurveyExecuteType.php
  src/Form/Type/SurveyNotifierType.php
  src/Form/Type/SurveyQuestionAlternativeType.php
  src/Form/Type/SurveyQuestionType.php
  src/Form/Type/SurveyType.php
  src/Repository/SurveyNotificationRepository.php
  src/Repository/SurveyRepository.php
  src/Repository/SurveyTakenRepository.php
  src/Service/SurveyManager.php
  src/Service/SurveyNotifier.php
  templates/adminBase.html.twig
  templates/base.html.twig
  templates/base/admin/main_navigation.html.twig
  templates/base/admin/mobile_navigation.html.twig
  templates/base/popup_lower.twig
  templates/control_panel/index.html.twig
  templates/control_panel/step_by_step/steps/step5.html.twig
  templates/survey/default_assistant_survey_notification_email.html.twig
  templates/survey/email_notification.html.twig
  templates/survey/email_notification_stylish.html.twig
  templates/survey/finish_page.html.twig
  templates/survey/notifier_create.html.twig
  templates/survey/notifiers.html.twig
  templates/survey/personal_email_notification.html.twig
  templates/survey/survey_create.html.twig
  templates/survey/survey_result.html.twig
  templates/survey/survey_table.html.twig
  templates/survey/surveys.html.twig
  templates/survey/takeSurvey.html.twig
  templates/widgets/available_surveys_widget.html.twig
  tests/Controller/SurveyPopUpControllerTest.php
Labels: hacktoberfest-accepted

#158 VB-116: Add dockerfile
  Dockerfile
  README.md
  composer.json
  package-lock.json
  package.json
  yarn.lock
Labels: hacktoberfest-accepted, PR: Reviewed with comments

#162 VB-77 Fileuploader, show error message
  src/Controller/ReceiptController.php
Labels: hacktoberfest-accepted, PR: Reviewed with comments

#185 VB-130: migrate annotation routes to routes yml
  config/routes.yaml
  src/Controller/AccessRuleController.php
  src/Controller/AdmissionAdminController.php
  src/Controller/AdmissionSubscriberController.php
  src/Controller/Api/AccountController.php
  src/Controller/AssistantController.php
  src/Controller/CertificateController.php
  src/Controller/ConfirmationController.php
  src/Controller/ContactController.php
  src/Controller/ExecutiveBoardController.php
  src/Controller/ExistingUserAdmissionController.php
  src/Controller/InterviewController.php
  src/Controller/SemesterController.php
  src/Controller/SponsorsController.php
  src/Controller/StandController.php
  src/Controller/TeamAdminController.php
  src/Controller/TeamApplicationController.php
  src/Controller/TeamInterestController.php
  src/Controller/UserController.php
Labels: PR: Needs Review

#203 VB-137 Remove gender-statistics-chart on homepage
  templates/home/chart_script.html.twig
  templates/home/index.html.twig
Labels: PR: Needs Review

#205 VB-142 fix: Add string as return type on getBlockPrefix
  src/Form/Type/AdmissionSubscriberType.php
  src/Form/Type/ApplicationExistingUserType.php
  src/Form/Type/ApplicationInterviewType.php
  src/Form/Type/ApplicationPracticalType.php
  src/Form/Type/ApplicationType.php
  src/Form/Type/AssignInterviewType.php
  src/Form/Type/CancelInterviewConfirmationType.php
  src/Form/Type/CreateAssistantHistoryType.php
  src/Form/Type/CreateDepartmentType.php
  src/Form/Type/CreateExecutiveBoardMembershipType.php
  src/Form/Type/CreateExecutiveBoardType.php
  src/Form/Type/CreateInterviewType.php
  src/Form/Type/CreatePositionType.php
  src/Form/Type/CreateSchoolType.php
  src/Form/Type/CreateSemesterType.php
  src/Form/Type/CreateTeamMembershipType.php
  src/Form/Type/CreateTeamType.php
  src/Form/Type/CreateUserOnApplicationType.php
  src/Form/Type/CreateUserType.php
  src/Form/Type/CropImageType.php
  src/Form/Type/DaysType.php
  src/Form/Type/EditAdmissionPeriodType.php
  src/Form/Type/EditUserPasswordType.php
  src/Form/Type/EditUserType.php
  src/Form/Type/FieldOfStudyType.php
  src/Form/Type/InterviewAnswerType.php
  src/Form/Type/InterviewNewTimeType.php
  src/Form/Type/InterviewQuestionAlternativeType.php
  src/Form/Type/InterviewQuestionType.php
  src/Form/Type/InterviewSchemaType.php
  src/Form/Type/InterviewScoreType.php
  src/Form/Type/InterviewType.php
  src/Form/Type/ModifySubstituteType.php
  src/Form/Type/NewPasswordType.php
  src/Form/Type/NewUserType.php
  src/Form/Type/PasswordResetType.php
  src/Form/Type/ScheduleInterviewType.php
  src/Form/Type/SchoolCapacityEditType.php
  src/Form/Type/SchoolCapacityType.php
  src/Form/Type/SponsorType.php
  src/Form/Type/SupportTicketType.php
  src/Form/Type/TeamApplicationType.php
  src/Form/Type/TeamInterestType.php
  src/Form/Type/TelType.php
  src/Form/Type/UserCompanyEmailType.php
  src/Form/Type/UserDataForSubstituteType.php
Labels: PR: Needs Review

#202 VB-135 Remove google-analytics
  .env
  config/packages/twig.yaml
  config/services.yaml
  templates/adminBase.html.twig
  templates/base.html.twig
Labels: PR: Needs Review

#200 VB-125 add assistant scheduling files
  src/AssistantScheduling/Assistant.php
  src/AssistantScheduling/School.php
Labels: hacktoberfest-accepted, PR: Needs Review
