Repository vektorprogrammet/vektor-backend, pull requests merged in 2022-12, with the labels that each got.

#246 VB-151 event subscriber files
  src/EventSubscriber/AccessControlSubscriber.php
  src/EventSubscriber/ApplicationSubscriber.php
  src/EventSubscriber/AssistantHistorySubscriber.php
  src/EventSubscriber/DbSubscriber.php
  src/EventSubscriber/ExceptionSubscriber.php
  src/EventSubscriber/GSuiteSubscriber.php
  src/EventSubscriber/InterviewSubscriber.php
  src/EventSubscriber/IntroductionEmailSubscriber.php
  src/EventSubscriber/ReceiptSubscriber.php
  src/EventSubscriber/SupportTicketSubscriber.php
  src/EventSubscriber/TeamApplicationSubscriber.php
  src/EventSubscriber/TeamInterestSubscriber.php
  src/EventSubscriber/TeamMembershipSubscriber.php
  src/EventSubscriber/UserSubscriber.php
  src/Service/CompanyEmailMaker.php
Labels: draft

#248 VB-142-update-project-name-in-composerjson
  composer.json
  templates/base/footer.html.twig
Labels: PR: Good to Merge

#247 Removed Oslo from footer
  assets/images/organizationstructure.png
  templates/about/about_vektor.html.twig
  templates/contact/index.html.twig
  templates/team/board_and_team.html.twig
Labels: PR: Reviewed with comments

#188 VB-124 updated from depricated encoder
  config/packages/security.yaml
  src/Controller/SsoController.php
Labels: hacktoberfest-accepted, PR: Reviewed with comments
